### PR TITLE
Generate Manifest via API, better clean-up on DeleteSpec

### PR DESCRIPTION
**Pull request by bodom0015**
* Adjusted `Generate Manifest` to use the new `/graph/convert` API endpoint
  * `Generate Manifest` was broken anyways, and this seemed easier than trying to fix it
* Modified DeleteSpec to clean up after itself a bit better
  * If the Spec exists in localStorage/on the current Canvas, it is deleted
    * Deleting a Spec while it exists on the Canvas otherwise would put the user into a bad state
  * Any saved Graph objects containing the deleted Spec are now deleted as well
    * Loading such a Graph would have put the user into a bad state

This fix is currently live on https://staging.cis.ndslabs.org for review

### CODE REVIEW

**Comment by craig-willis** [comment]
Being lazy -- is this running somewhere I can test.  The hackathon.cis site is returning `
{{ reformat(legacyMode) }}` on the generate manifest.

**Comment by bodom0015** [comment]
Sorry, it was running on dev.cis.ndslabs.org before I swapped branches and started making PRs

I'll run one at https://staging.cis.ndslabs.org too for testing

**Comment by bodom0015** [comment]
This should now be running at https://staging.cis.ndslabs.org/#/ for you to test

**Comment by craig-willis** [comment]
All looks great. Thank you for facilitating my laziness.

**Pull request merged**
